name: Build Plugin
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v5

      - name: Cài đặt Java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Biên dịch với Maven
        run: mvn clean package --no-transfer-progress --batch-mode

      - name: Lưu tệp kết quả
        uses: actions/upload-artifact@v5
        with:
          name: WeeklyQuests-Plugin
          path: target/WeeklyQuests.jar
